import pandas as pd

data = {
    "order_id": [
        1001,1002,1003,1004,1005,
        1006,1007,1008,1009,1010,
        1011,1012,1013,1014,1015,
        1016,1017,1018,1019,1020
    ],

    "date": [
        "2024-01-01","2024-01-02","2024-01-03","2024-01-04","2024-01-05",
        "2024-01-06","2024-01-07","2024-01-08","2024-01-09","2024-01-10",
        "2024-01-11","2024-01-12","2024-01-13","2024-01-14","2024-01-15",
        "2024-01-16","2024-01-17","2024-01-18","2024-01-19","2024-01-20"
    ],

    "city": [
        "Kolkata","Delhi","Mumbai","Kolkata","Chennai",
        "Delhi","Mumbai","Kolkata","Delhi","Chennai",
        "Mumbai","Kolkata","Delhi","Mumbai","Chennai",
        "Kolkata","Delhi","Mumbai","Kolkata","Chennai"
    ],

    "category": [
        "Electronics","Clothing","Groceries","Electronics","Clothing",
        "Electronics","Clothing","Groceries","Electronics","Clothing",
        "Groceries","Electronics","Clothing","Groceries","Electronics",
        "Clothing","Groceries","Electronics","Clothing","Groceries"
    ],

    "selling_price": [
        12000,1500,800,22000,2500,
        18000,2000,950,26000,3000,
        1100,14000,1700,900,24000,
        2100,800,23000,3200,1000
    ],

    "cost_price": [
        9000,800,600,16000,1500,
        13500,1200,700,19000,1800,
        700,10000,1100,650,18000,
        1400,600,17000,2100,700
    ],

    "quantity": [
        1,2,5,1,3,
        1,2,6,1,2,
        4,1,3,5,1,
        2,6,1,2,4
    ],

    "discount_percent": [
        10,5,0,15,5,
        10,5,0,20,10,
        0,10,5,0,15,
        5,0,10,5,0
    ],

    "shipping_cost": [
        150,80,40,200,90,
        180,85,45,220,100,
        50,160,90,40,210,
        85,45,190,95,50
    ],

    "tax_percent": [
        18,12,5,18,12,
        18,12,5,18,12,
        5,18,12,5,18,
        12,5,18,12,5
    ],

    "payment_method": [
        "UPI","Card","Cash","UPI","Card",
        "UPI","Card","Cash","UPI","Card",
        "Cash","UPI","Card","Cash","UPI",
        "Card","Cash","UPI","Card","Cash"
    ],

    "returned": [
        False,False,False,True,False,
        False,False,False,False,True,
        False,False,False,False,False,
        False,False,False,True,False
    ]
}

df = pd.DataFrame(data)
df["date"] = pd.to_datetime(df["date"])

df["revenue"] = df["selling_price"] * df["quantity"]
total_revenue = df["revenue"].sum()
print("Total Revenue: ",total_revenue)

df.loc[df["returned"], "revenue"] = 0
print("Total Revenue after returns: ", df["revenue"].sum())
print(df.head())

# Revenue by city
revenue_city=df.groupby('city')["revenue"].sum()
print("Revenue by City: \n", revenue_city)
# Revenue by category
revenue_category=df.groupby("category")["revenue"].sum()
print("Revenue by Category: ", revenue_category)
# Daily revenue trend
daily_revenue=df.groupby("date")["revenue"].sum()
print("Daily Revenue Trend: ", daily_revenue)

print("Top cities by Revenue: ", df.groupby('city')['revenue'].sum().sort_values(ascending=False).head(3))
print("Top Category by Revenue: ",df.groupby("category")["revenue"].sum().sort_values(ascending=False).head(3))


print("The Top revenue generating city is: ", revenue_city.idxmax())
print("The lowest revenue generating city is: ", revenue_city.idxmin())
print("The highest revenue generating category is: ", revenue_category.idxmax())
print("The lowest revenue generating category is: ", revenue_category.idxmin())
print("Average revenue per order: ", df["revenue"].mean())
print("The Highest Revenue generated in a single order is: ", df["revenue"].max())
print("The Lowest Revenue generated by an order is: ",df["revenue"].min())
print("Daily revenue trend sorted by date: ", daily_revenue.sort_index())


df["discount_amount"] = df["revenue"] * df["discount_percent"] / 100
print("Total Discount Given: ", df["discount_amount"].sum())

df["net_revenue"] = df["revenue"] - df["discount_amount"]
print("Total Net Revenue: ", df["net_revenue"].sum())

df["tax_amount"] = df["net_revenue"] * df["tax_percent"] / 100
print("Total Tax Collected: ", df["tax_amount"].sum())

df["total_cost"] = df["cost_price"] * df["quantity"] + df["shipping_cost"]
print("Total Cost Incurred: ", df["total_cost"].sum())

df["profit"] = df["net_revenue"] - df["total_cost"] - df["tax_amount"]
print("Total Profit Made: ", df["profit"].sum())

df["city_category"] = df["city"].apply(lambda x: 'Metro' if x in ['Delhi', 'Mumbai'] else ('Urban' if x in ['Kolkata', 'Chennai'] else 'Other'))
print("Data with City Category: ", df)

df["quantity_type"] = df["quantity"].apply(lambda x: 'Bulk' if x >=5 else 'Regular')
print("Data with Quantity Type: ", df)

df["selling_type"] = df['selling_price'].apply(lambda x: 'Luxury' if x>20000 else 'Non luxury')
print("Data with Selling Type: ", df)

df["order_value_type"] = df['revenue'].apply(lambda x: 'High Value' if x>=20000 else 'Standard')
print("Data with Order Value Type: ", df)

import plotly.express as px
fig = px.bar(revenue_city, x=revenue_city.index, y=revenue_city.values, title='Total Revenue by City', labels={'x':'City', 'y':'Total Revenue'})
fig.show()
fig = px.bar(revenue_category, x=revenue_category.index, y=revenue_category.values, title='Total Revenue by Category', labels={'x':'Category', 'y':'Total Revenue'})
fig.show()
fig = px.line(daily_revenue.sort_index(), x=daily_revenue.sort_index().index, y=daily_revenue.sort_index().values, title='Daily Revenue Trend', labels={'x':'Date', 'y':'Daily Revenue'})
fig.show()


# Few words for the dataset analysis
print("The dataset provides a comprehensive overview of e-commerce transactions over a 20-day period across multiple cities and product categories. Key performance indicators such as total revenue, net revenue, discounts, taxes, costs, and profits have been calculated to assess the financial health of the business.")
print("The analysis reveals that certain cities and product categories significantly outperform others in terms of revenue generation. For instance, the top revenue-generating city and category have been identified, providing insights into market preferences and potential areas for growth.")
print("Daily revenue trends highlight fluctuations in sales, which could be influenced by factors such as promotions, holidays, or market conditions. Understanding these patterns can aid in strategic planning and inventory management.")
print("The breakdown of payment methods indicates customer preferences, which can inform future payment options and marketing strategies")
print("Overall, this analysis serves as a valuable tool for decision-making, enabling stakeholders to optimize operations, enhance customer satisfaction, and drive business growth in the competitive e-commerce landscape.")
