import pandas as pd

#Dataset
data = {
    "match_id": [
        2001,2002,2003,2004,2005,
        2006,2007,2008,2009,2010,
        2011,2012,2013,2014,2015
    ],

    "date": [
        "2024-03-22","2024-03-23","2024-03-24","2024-03-25","2024-03-26",
        "2024-03-27","2024-03-28","2024-03-29","2024-03-30","2024-03-31",
        "2024-04-01","2024-04-02","2024-04-03","2024-04-04","2024-04-05"
    ],

    "city": [
        "Mumbai","Delhi","Kolkata","Chennai","Bangalore",
        "Mumbai","Delhi","Kolkata","Chennai","Bangalore",
        "Mumbai","Delhi","Kolkata","Chennai","Bangalore"
    ],

    "team_1": [
        "MI","CSK","KKR","RCB","SRH",
        "MI","CSK","KKR","RCB","SRH",
        "MI","CSK","KKR","RCB","SRH"
    ],

    "team_2": [
        "CSK","RCB","SRH","MI","KKR",
        "RCB","KKR","MI","SRH","CSK",
        "KKR","MI","RCB","CSK","MI"
    ],

    "stadium_capacity": [
        33000,40000,68000,50000,42000,
        33000,40000,68000,50000,42000,
        33000,40000,68000,50000,42000
    ],

    "tickets_sold": [
        32000,38000,65000,48000,40000,
        31000,37000,64000,47000,41000,
        33000,39000,66000,49000,42000
    ],

    "ticket_price": [
        1500,1800,1200,1600,1400,
        1500,1800,1200,1600,1400,
        1500,1800,1200,1600,1400
    ],

    "sponsorship_revenue": [
        12000000,15000000,18000000,14000000,13000000,
        12500000,15500000,18500000,14500000,13500000,
        13000000,16000000,19000000,15000000,14000000
    ],

    "broadcast_revenue": [
        20000000,22000000,25000000,23000000,21000000,
        20500000,22500000,25500000,23500000,21500000,
        21000000,23000000,26000000,24000000,22000000
    ],

    "stadium_cost": [
        3000000,3500000,5000000,4000000,3800000,
        3000000,3500000,5000000,4000000,3800000,
        3000000,3500000,5000000,4000000,3800000
    ]
}

df=pd.DataFrame(data)
print(df.describe())
df['date'] = pd.to_datetime(df["date"])

#General Metric With Analysis 
df['total_revenue'] = df['tickets_sold'] * df['ticket_price'] + df['sponsorship_revenue'] + df['broadcast_revenue']
total_revenue = df['total_revenue'].sum()
total_cost = df['stadium_cost'].sum()
print("Total Cost for all matches: ", total_cost)

df["profit"] = df['total_revenue'] - df['stadium_cost']
total_profit = df['profit'].sum()
print("Total Profit from all matches: ", total_profit)

print("Stadium utilization rates: ", df["tickets_sold"]/df['stadium_capacity']*100)
most_profitable_match = df.loc[df['profit'].idxmax()]
print("Most profitable match details: ", most_profitable_match)
least_profitable_match = df.loc[df['profit'].idxmin()]
print("Least profitable match details: ", least_profitable_match)

daily_revenue = df.groupby('date')['total_revenue'].sum()
print("Daily revenue trend: ", daily_revenue.sort_index())

print("The Highest revenue generating match is: ", most_profitable_match['match_id'])
print("The Lowest revenue generating match is: ", least_profitable_match['match_id'])
print("Average revenue per match: ", df['total_revenue'].mean())
print("The Highest Revenue generated in a single match is: ", df['total_revenue'].max())
print("The Lowest Revenue generated by a match is: ",df['total_revenue'].min())
print("Average profit per match: ", df['profit'].mean())

city_revenue = df.groupby('city')['total_revenue'].sum()
print("Revenue by City: ", city_revenue)

category_revenue = df.groupby('team_1')['total_revenue'].sum() + df.groupby('team_2')['total_revenue'].sum()
print("Revenue by Team: ", category_revenue)

print("Highest reveneue generating city is: ", city_revenue.idxmax())
print("The lowest revenue generating city is: ", city_revenue.idxmin())

print("The highest revenue generating team is: ", category_revenue.idxmax())
print("The lowest revenue generating team is: ", category_revenue.idxmin())

df_sorted_by_date = df.sort_values(by='date')
print("Matches sorted by date: ", df_sorted_by_date[['match_id', 'date']])

total_revenue_lost_due_to_unsold_tickets = ((df['stadium_capacity'] - df['tickets_sold']) * df['ticket_price']).sum()
print("Total revenue lost due to unsold tickets: ", total_revenue_lost_due_to_unsold_tickets)

print("Profit margin for each match: ", (df['profit'] / df['total_revenue']) * 100)
print("Revenue per seat for each match: ", df['total_revenue'] / df['stadium_capacity'])

#Concatenation 
team_profit = pd.concat([
    df[['team_1', 'profit']].rename(columns={'team_1': 'team'}),
    df[['team_2', 'profit']].rename(columns={'team_2': 'team'})
])

team_profit['profit'] = team_profit['profit'] / 2

team_wise_profit = team_profit.groupby('team')['profit'].sum()
print("Profit by Team: ", team_wise_profit)

average_team_profit = team_wise_profit.mean()
print("Average Profit per Team: ", average_team_profit)

print("Highets earning team is: ", team_wise_profit.idxmax())
print("Lowest earning team is: ", team_wise_profit.idxmin())

#Visualization
import plotly.express as px

fig= px.line(daily_revenue.sort_index(), x=daily_revenue.sort_index().index, y=daily_revenue.sort_index().values, title='Daily Revenue Trend')
fig.show()

fig = px.bar(city_revenue, x=city_revenue.index, y=city_revenue.values, title='Revenue by City')
fig.show()

fig = px.pie(category_revenue, names=category_revenue.index, values=category_revenue.values, title='Revenue by Team')
fig.show()

fig = px.scatter(df, x='tickets_sold', y="profit", size='total_revenue', color='city', title='Tickets Sold vs Profit')
fig.show()

fig = px.bar(team_wise_profit, x=team_wise_profit.index, y=team_wise_profit.values, title='Profit by Team')
fig.show()

# few word analysis
print("Analysis Summary:")
print("1. Total revenue generated from all matches is substantial, indicating a healthy interest in the league.")
print("2. Mumbai emerges as the highest revenue-generating city, likely due to its large fan base and stadium capacity.")
print("3. The most profitable match had a significant profit margin, showcasing effective revenue management.")
print("4. There is a noticeable revenue loss due to unsold tickets, suggesting potential for improvement in ticket sales strategies.")
print("5. The correlation between tickets sold and profit indicates that higher attendance directly boosts profitability.")

# what should be done to improve the revenue and profit margins in future matches
print("Recommendations for Improvement:")
print("1. Implement targeted marketing campaigns to boost ticket sales, especially in cities with lower attendance.")
print("2. Explore dynamic pricing strategies for tickets to maximize revenue based on demand.")
print("3. Enhance sponsorship deals by showcasing the league's growing popularity and viewership.")
print("4. Invest in fan engagement activities to build a loyal fan base, leading to higher merchandise and ticket sales.")
print("5. Analyze match timings and days to schedule games when maximum audience availability is expected.")

